#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x7A1C87E3F5BC42A8 (davidism@gmail.com)
#
Name     : deprecated-Jinja2
Version  : 2.10
Release  : 59
URL      : http://pypi.debian.net/Jinja2/Jinja2-2.10.tar.gz
Source0  : http://pypi.debian.net/Jinja2/Jinja2-2.10.tar.gz
Source99 : http://pypi.debian.net/Jinja2/Jinja2-2.10.tar.gz.asc
Summary  : A small but fast and easy to use stand-alone template engine written in pure python.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: deprecated-Jinja2-license = %{version}-%{release}
Requires: deprecated-Jinja2-python = %{version}-%{release}
Requires: Babel
Requires: MarkupSafe
BuildRequires : MarkupSafe
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : deprecated-MarkupSafe-legacypython

%description
Flask Sphinx Styles
===================
This repository contains sphinx styles for Flask and Flask related
projects.  To use this style in your Sphinx documentation, follow
this guide:

%package legacypython
Summary: legacypython components for the deprecated-Jinja2 package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-Jinja2 package.


%package license
Summary: license components for the deprecated-Jinja2 package.
Group: Default

%description license
license components for the deprecated-Jinja2 package.


%package python
Summary: python components for the deprecated-Jinja2 package.
Group: Default
Provides: deprecated-jinja2-python

%description python
python components for the deprecated-Jinja2 package.


%prep
%setup -q -n Jinja2-2.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554336625
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-Jinja2
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-Jinja2/LICENSE
cp docs/_themes/LICENSE %{buildroot}/usr/share/package-licenses/deprecated-Jinja2/docs__themes_LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-Jinja2/LICENSE
/usr/share/package-licenses/deprecated-Jinja2/docs__themes_LICENSE

%files python
%defattr(-,root,root,-)
